### ISSUE TITLE
Can't export properly

### ISSUE THREAD

**Issue by guestisp** [mapbox/mbutil#105]
I'm trying to export raster tiles from these MBTiles:
https://openmaptiles.com/downloads/tileset/osm/europe/albania/

but exported images are not properly saved as png (or any other image format)

Any idea ?

**Comment by agoudsmit** [comment]
same issue: Running 
./mb-util osm-2017-07-03-v3.6.1-europe_netherlands.mbtiles\?usage\=personal tiles
and i get broken images, 78bytes

**Comment by ajashton** [comment]
Hi,

Those MBTiles files contain vector tiles, not raster tiles. `mbutil` cannot convert vector tiles to raster tiles, and I'm not aware of a tool that will allow you to do this easily offline & in bulk. The problem is vector tiles are just data with no styling information - you need a tool that can apply a style to the vector data & render images.
