### ISSUE TITLE
Would it be possible to create uncompressed .pbf from an .mbtiles

### ISSUE THREAD

**Issue by nouryf** [mapbox/mbutil#79]
Hi, 

When extracting the tiles as .pbf from an .mbtiles these seems to be ziped. Before being able to consume them from a client using .js they need to be uncompressed first. Would it be possible to have an option to produce uncompressed .pbf ? This way the process of creating uncompressed .pbf can be done in one step.

Thanks

**Comment by ImreSamu** [comment]
> Before being able to consume them from a client using .js they need to be uncompressed first.

check the:  https://github.com/mapbox/awesome-vector-tiles  you can find lot of JavaScript tools  ...

**Comment by nouryf** [comment]
Thanks. I can unzip the pbf files just ok but i was wondering if it's possible to produce/extract uncompressed .pbf directly when using mbutil. This way the process of having ready to consume .pbf will be simply one step: mbutil and not two steps: mbutil then looping through the folders and sub-folders to uncompress the .pbf one by one.

**Comment by sgillies** [comment]
@nouryf this project is not actively developed and we are not taking requests for new features. We will, however, gladly accept pull requests with tested code.

**Comment by anilkunchalaece** [comment]
[pull request](https://github.com/mapbox/mbutil/pull/109)
will solve the problem , i think

**Comment by marjanmo** [comment]
Just a tip for those who are stuck "_looping through the folders and sub-folders to uncompress the .pbf one by one._". Mb-util actually exports gzip compressed files, but the names (.pbf) do not suggest that. In order to actually decompress them, you have to rename them first into (.pbf.gz). So after the mb-util conversion, this is what did the trick for me to end up with the same output structure, only with actually decompressed pbf files:

```
cd output_dir
find . -name '*.pbf' -exec bash -c 'mv "$1" "${1}".gz' - '{}' \;
find . -name '*.gz' -exec bash -c 'gzip -d "$1"' - '{}' \;
```
