### ISSUE TITLE
error when export large size mbtiles

### ISSUE THREAD

**Issue by yangdonglai** [mapbox/mbutil#97]
when I use mb-util to export tile from a  52G mbtiles file, the process always stop when export about 26G.

it throw  **[Errno 28] No space left on device**, but I comfirm there is still  69G available.

I try times and it always stop when export about 26G.
![image](https://user-images.githubusercontent.com/17786362/37818757-47262666-2eb6-11e8-87b2-23ce29ce2330.png)
![image](https://user-images.githubusercontent.com/17786362/37818814-6d2e21ec-2eb6-11e8-9529-fc287fa12a70.png)

**Comment by ajashton** [comment]
Hi,

Your disk is probably running out of `inodes` - you can confirm this with `df -i`. File systems can only hold so many individual files, even if the total size of those files is much less than the number of GB available. (This problem was one reason for the idea packing tiles into MBTiles in the first place.)

You may need to look at processing your tiles in batches. I'm not sure about other possible workarounds.

**Comment by yangdonglai** [comment]
@ajashton Thank You!!!  Yes, there is no available `inodes`.
I will close this issue.
But I am still curious about one thing. Could you help me.
Which is the better way to serve a mbtiles with such large size?
 [mbview](https://github.com/mapbox/mbview) (a simple server code using `express` and `sqlite`) or `nginx` after `mb-util` the mbtiles to static pbf file.

**Comment by F3L1X79** [comment]
I ran into the same issue today - what do you mean exactly by 'processing your tiles in batches'? Is it possible to extract the tiles 10% by 10%?

**Comment by F3L1X79** [comment]
moreover, is it possible to clean and liberates some `inodes` whithout breaking anything? I guess it's a problem to have them 100% on a production server...
